# 0️⃣ 建立虛擬環境（建議）

## 0.1 建立虛擬環境

> 先安裝python ver.9 ，因為有一些有特別的依賴在新的環境中沒辦法用

```shell
py -3.9 -m venv bert_env
bert_env\Scripts\activate

## 0.2 註冊jupyter運行

```shell
py -3.9 -m venv bert_env
bert_env\Scripts\activate
```

## 0.3 安裝troch

```shell
pip install ipykernel
python -m ipykernel install --user --name=bert_env --display-name "Python (bert_env)"
```

## 0.4 安裝需要的庫

### 方法一，直接載入

> 先將下面的資訊複製貼上到txt檔，並將名稱命名為requirements.txt

```shell
aiohappyeyeballs==2.6.1
aiohttp==3.12.13
aiosignal==1.3.2
annotated-types==0.7.0
anyio==4.9.0
argon2-cffi==25.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.5
async-timeout==5.0.1
attrs==25.3.0
babel==2.17.0
beautifulsoup4==4.13.4
bertopic==0.17.0
bleach==6.2.0
blis==0.7.11
catalogue==2.0.10
certifi==2025.6.15
cffi==1.17.1
charset-normalizer==3.4.2
click==8.1.8
colorama==0.4.6
comm==0.2.2
confection==0.1.5
cymem==2.0.11
datasets==3.6.0
debugpy==1.8.14
decorator==5.2.1
defusedxml==0.7.1
dill==0.3.8
distro==1.9.0
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl
exceptiongroup==1.3.0
executing==2.2.0
fastjsonschema==2.21.1
filelock==3.13.1
fqdn==1.5.1
frozenlist==1.7.0
fsspec==2024.6.1
h11==0.16.0
hdbscan==0.8.40
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.33.0
idna==3.10
importlib_metadata==8.7.0
ipykernel==6.29.5
ipython==8.18.1
ipywidgets==8.1.7
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.4
jiter==0.10.0
joblib==1.5.1
json5==0.12.0
jsonpointer==3.0.0
jsonschema==4.24.0
jsonschema-specifications==2025.4.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.8.1
jupyter_server==2.16.0
jupyter_server_terminals==0.5.3
jupyterlab==4.4.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.15
langcodes==3.5.0
language_data==1.3.0
llvmlite==0.43.0
marisa-trie==1.2.1
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.1.3
mpmath==1.3.0
multidict==6.5.0
multiprocess==0.70.16
murmurhash==1.0.13
narwhals==1.43.0
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.2.1
nltk==3.9.1
notebook==7.4.3
notebook_shim==0.2.4
numba==0.60.0
numpy==1.26.3
openai==1.88.0
overrides==7.7.0
packaging==25.0
pandas==2.3.0
pandocfilters==1.5.1
parso==0.8.4
pathlib_abc==0.1.1
pathy==0.11.0
pillow==11.0.0
platformdirs==4.3.8
plotly==6.1.2
preshed==3.0.10
prometheus_client==0.22.1
prompt_toolkit==3.0.51
propcache==0.3.2
psutil==7.0.0
pure_eval==0.2.3
pyarrow==20.0.0
pycparser==2.22
pydantic==1.10.22
pydantic_core==2.33.2
Pygments==2.19.1
pynndescent==0.5.13
python-dateutil==2.9.0.post0
python-json-logger==3.3.0
pytz==2025.2
pywin32==310
pywinpty==2.0.15
PyYAML==6.0.2
pyzmq==27.0.0
referencing==0.36.2
regex==2024.11.6
requests==2.32.4
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.25.1
safetensors==0.5.3
scikit-learn==1.6.1
scipy==1.13.1
Send2Trash==1.8.3
sentence-transformers==4.1.0
six==1.17.0
smart-open==6.4.0
sniffio==1.3.1
soupsieve==2.7
spacy==3.5.3
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.5.1
stack-data==0.6.3
sympy==1.13.3
terminado==0.18.1
thinc==8.1.12
threadpoolctl==3.6.0
tinycss2==1.4.0
tokenizers==0.21.1
tomli==2.2.1
tornado==6.5.1
tqdm==4.67.1
traitlets==5.14.3
transformers==4.52.4
typer==0.7.0
types-python-dateutil==2.9.0.20250516
typing-inspection==0.4.1
typing_extensions==4.14.0
tzdata==2025.2
umap-learn==0.5.7
uri-template==1.3.0
urllib3==2.4.0
wasabi==1.1.3
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.14
xxhash==3.5.0
yarl==1.20.1
zipp==3.23.0
```

#### 在cmd輸入

```shell
pip install -r requirements.txt
```

### 方法二：手動下載

```shell
pip install bertopic
pip install sentence-transformers umap-learn
pip install ipywidgets --upgrade
pip install jupyter --upgrade

pip install widgetsnbextension
pip install openai
pip install datasets
pip install nltk

pip install spacy==3.5.3
pip install bertopic[spacy]
python -m spacy download en_core_web_sm
```

# 1️⃣ 設定

## 1.1 設定數據集

In [11]:
from datasets import load_from_disk

# 載入HuggingFace Dataset
dataset = load_from_disk("./transcript_dataset")

## 1.2 驗證載入結果

In [12]:
# 驗證載入結果
print(f"載入的資料集: {dataset}")
print(f"第一筆資料: {dataset[0]}")

載入的資料集: Dataset({
    features: ['title', 'transcript'],
    num_rows: 454
})
第一筆資料: {'title': '#AskPorsche ¦¦ Part 01   The name Turbo, sound and costs of the Taycan and further electrification (1080p 25fps H264 128kbit AAC)', 'transcript': "Hello and welcome to Ask Porsche. I'm Alex and this is Andi from Porsche. Hi. We're here in the studio in Stuttgart-Zuffenhausen and I will be asking him your questions about this beautiful car, the Taycan, Porsche's first all-electric car. Turbo means much more to us. Does it really make that sound? In reality, it's even cooler. Big thing will be the all-electric Macan successor. I'm standing next to Taycan because the question we have is regarding this car's name and Vela wants to know, it's electric, why does it need turbo? So Andi, does this car have a turbo? No, but turbo means much more to us. Actually, it's a promise. It's a promise about performance, about driving dynamics, about acceleration, about... Top speed. It's always a top of the line derivative actually, but it's also about heritage. Look at that beauty. Second sexy car. Yeah, back in the 70s, we were introducing the first turbo derivative from Porsche. And as all the other Porsche models that have a turbo derivative like Panamera, 911, Macan, we are really sure that the Taycan turbo also deserves that badge. Andi, thank you. That makes a lot of sense to me now. And Vela, trust me, I've driven this bad boy before. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. I'm not going to lie to you. And from my personal experience, I can tell you it's an amazing top of the line Porsche sports car. So it's well deserving of the name turbo. Thanks for asking this great question and onto the next one. Everybody knows Porsche builds beautiful cars that also sound great. I found another great question under one of the Taycan's YouTube videos. And Yannick wants to know, does it really make that sound they use in the ads? And if yes, where does it come from? Let's have a look. So Andy, does it really make that sound? Absolutely. I would say in reality, it's even cooler. Maybe we can test it here in the car. I would love to. So sport plus and launch control. Sport plus. I know how to do it. Foot on the brake, go and drive. And now it's music. Sweet, sweet music. I really would love to go now. Can't do that. We spend a lot of time with the engineers to come up with that Porsche electric sports sound. We want to have it first authentic. Then it should be futuristic. And then it should give you as a driver feedback on what the car is really doing. Now, where does the sound actually come from? The sound is basically derived from the powertrain component itself. The electric motors, the power electronics and the transmission. Based on that, we amplified it and came up with a Porsche electric sports sound. Andy, thank you for that explanation. Yannick, the sound is real, just like in the ad. Thank you for this great question. I wish I could drive now. Can't do that. But what I can do is see you in the next video. Andy, what a great job you guys have done with your first electric car. Many people, including me, would love to have one. And Emil, you sent a funny question. Let's see what our Porsche expert suggests. Ready for this? Okay, bring it on. Which of my body parts do I need to sell to get this car? That's really a funny one. To be honest, I'm not sure if that's compliant to pay the car with one of your body parts. Probably not, but let's pretend it was. Definitely not the ears, because you want to hear the electric sports sound, right? Yeah, for sure. Not the hands. You need them for driving and you want to feel the car. But you don't need to shift. I would go for the left leg. Oh, no. Joking aside, if he really wants to drive the new Taycan, he can book a Porsche driving experience. Boom, Emil. See, that's your solution. You can drive the car on a racetrack. With all your body parts intact. Thank you for your funny question. Hey guys, we are back with a question from a curious Porsche fan. In the background, the beautiful all-electric Porsche Taycan. So, the question is, which model is going to be electrified next? First of all, I'd like to mention that we see a lot of potential for that model line, the Taycan. If you cross-check with other model lines to do a base version of that and maybe some other versions too. But I can't tell you right now. But you are talking about multiple versions of the Taycan. Okay. And there will be another body style. Have you heard about the Cross Tourism? Tell me about it. More lifestyle-orientated with some SUV features and it will be a really cool car. Does it mean it's going to be bigger? Maybe. He can't let us know everything, but he gave us some hints. Might there be some Porsche models that already exist today that will be electrified? There is more to come. New Taycan versions, another body style and the next big thing that we are going to talk about is the Cross Tourism. The next big thing will be the all-electric Macan successor. All-electric like this baby right here. Exactly. It will be a battery electric vehicle, purpose-designed. Thank you for the outlook in the company's future. That should answer your question. Thank you for asking it. And we see you soon. Guys, thank you for your interest. We hope you enjoyed this. Goodbye for now from Stuttgart-Zoffenhausen. Bye for now."}

## 1.3 資料及驗證

In [13]:
def validate_dataset(dataset):
    """
    驗證資料集格式和內容
    """
    print("=== 資料集驗證 ===")
    print(f"資料筆數: {len(dataset)}")
    print(f"欄位: {list(dataset.features.keys())}")
    
    # 檢查前幾筆資料
    print("\n前3筆資料範例:")
    for i in range(min(3, len(dataset))):
        print(f"\n第 {i+1} 筆:")
        print(f"標題: {dataset[i]['title'][:50]}...")
        print(f"內容: {dataset[i]['transcript'][:100]}...")
    
    # 統計資訊
    transcript = dataset['transcript']
    word_counts = [len(text.split()) for text in transcript[:100]]  # 取樣100筆
    print(f"\n平均字數: {sum(word_counts) / len(word_counts):.1f}")

In [14]:
# 驗證資料集
validate_dataset(dataset)

=== 資料集驗證 ===
資料筆數: 454
欄位: ['title', 'transcript']

前3筆資料範例:

第 1 筆:
標題: #AskPorsche ¦¦ Part 01   The name Turbo, sound and...
內容: Hello and welcome to Ask Porsche. I'm Alex and this is Andi from Porsche. Hi. We're here in the stud...

第 2 筆:
標題: #AskPorsche ¦¦ Part 02   Performance in winter, ac...
內容: Hello and welcome to Ask Porsche. I'm Alex and this is Andi from Porsche. Hi. We're here in the stud...

第 3 筆:
標題: #AskPorsche ¦¦ Part 03   Design challenges, chargi...
內容: Hello and welcome to Ask Porsche. I'm Alex and this is Andi from Porsche. Hi. We're here in the stud...

平均字數: 1111.7

## 1.4 準備分析用的資料

In [15]:
# 提取標題和內容，與原始程式碼格式一致
transcript = dataset['transcript']
titles = dataset['title']

print(f"成功準備 {len(transcript)} 筆逐字稿資料")
print(f"標題範例: {titles[0]}")
print(f"內容範例: {transcript[0][:200]}...")

# 現在可以使用與之前相同的分析流程
# 例如：文本摘要、關鍵字提取等

成功準備 454 筆逐字稿資料
標題範例: #AskPorsche ¦¦ Part 01   The name Turbo, sound and costs of the Taycan and further electrification (1080p 25fps H264 128kbit AAC)
內容範例: Hello and welcome to Ask Porsche. I'm Alex and this is Andi from Porsche. Hi. We're here in the studio in Stuttgart-Zuffenhausen and I will be asking him your questions about this beautiful car, the T...

# 2️⃣ 數據清理與處理

## 2.1 句子拆分

### 下載必要資料

In [16]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\yoyo9\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### 切分

In [17]:
from nltk.tokenize import sent_tokenize, word_tokenize
sentences = [sent_tokenize(transcript) for transcript in transcript]
sentences = [sentence for doc in sentences for sentence in doc]

### 驗證切分

In [18]:
print(f"總共有 {len(sentences)} 句話")

# 只印出前幾句（最簡單、最推薦）
for i, s in enumerate(sentences[:10]):
    print(f"{i+1}. {s}")

總共有 39033 句話
1. Hello and welcome to Ask Porsche.
2. I'm Alex and this is Andi from Porsche.
3. Hi.
4. We're here in the studio in Stuttgart-Zuffenhausen and I will be asking him your questions about this beautiful car, the Taycan, Porsche's first all-electric car.
5. Turbo means much more to us.
6. Does it really make that sound?
7. In reality, it's even cooler.
8. Big thing will be the all-electric Macan successor.
9. I'm standing next to Taycan because the question we have is regarding this car's name and Vela wants to know, it's electric, why does it need turbo?
10. So Andi, does this car have a turbo?

## 2.2 清理其中的廠商、模型名稱

### 定義清理資料的函式

In [19]:
def remove_brands_case_sensitive(text):
    """
    移除品牌關鍵字（大小寫敏感，只移除大寫版本）
    這個方法比較安全，因為一般品牌名都是大寫開頭
    """
    BRAND_KEYWORDS = ['Bentley Motors', 'Lucid', 'Scion', 'Cadillac', 'Hyundai', 'Mercedes-Benz', 'BYD', 
                      'Acura', 'Saturn', 'Lexus', 'Nissan', 'Karma', 'Mazda', 'Rolls-Royce',
                      'Wheego Electric Cars, Inc.', 'McLaren', 'Genesis', 'Chrysler', 'Volkswagen', 'Coda Automotive',
                      'Fiat', 'Infiniti', 'Buick', 'Chevrolet', 'Kandi', 'Lincoln', 'Porsche', 'Tesla', 'Mitsubishi', 
                      'Audi', 'Volvo', 'Honda', 'BMW', 'Dodge', 'Ford', 'Maserati', 'Toyota', 'Fisker Automotive',
                      'Ferrari', 'Kia', 'Mercury', 'Bugatti Rimac', 'Polestar']
    
    pattern = r"\b(" + "|".join(re.escape(word) for word in BRAND_KEYWORDS) + r")\b"
    return re.sub(pattern, "", text)

In [20]:
def clean_text_improved(text):
    """
    改進的文本清理函數
    """
    # 選擇其中一種品牌移除方法
    text = remove_brands_case_sensitive(text)  # 或使用 remove_brands_whole_word(text)
    
    # 移除多餘空白
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

### 應用清洗，再送入模型

In [25]:
import re
sentences = [clean_text_improved(s) for s in sentences]

### 驗證清理

In [26]:
print(f"總共有 {len(sentences)} 句話")

# 只印出前幾句（最簡單、最推薦）
for i, s in enumerate(sentences[:10]):
    print(f"{i+1}. {s}")

總共有 39033 句話
1. Hello and welcome to Ask .
2. I'm Alex and this is Andi from .
3. Hi.
4. We're here in the studio in Stuttgart-Zuffenhausen and I will be asking him your questions about this beautiful car, the Taycan, 's first all-electric car.
5. Turbo means much more to us.
6. Does it really make that sound?
7. In reality, it's even cooler.
8. Big thing will be the all-electric Macan successor.
9. I'm standing next to Taycan because the question we have is regarding this car's name and Vela wants to know, it's electric, why does it need turbo?
10. So Andi, does this car have a turbo?

# 3️⃣ 模型預先設定

## 3.1 預先計算嵌入

在創建了我們的數據（即摘要 ）之後，我們可以深入研究第一個最佳實踐， 即預先計算嵌入 。

BERTopic 的工作原理是將文檔轉換為稱為嵌入的數值。這個過程可能非常昂貴，特別是當我們想反覆運算參數時。相反，我們可以計算一次這些嵌入，然後將它們提供給 BERTopic 以跳過每次計算嵌入。

In [27]:
from sentence_transformers import SentenceTransformer

# Pre-calculate embeddings
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

Batches:   0%|          | 0/1220 [00:00<?, ?it/s]

## 3.2 防止隨機行為

在 BERTopic 中，我們通常使用降維演算法來減小嵌入的大小。這樣做是為了在一定程度上防止維度的詛咒 。

默認情況下，這是通過 UMAP 完成的，UMAP 是一種用於減少維度空間的不可思議的演算法。但是，默認情況下，它顯示隨機行為，每次運行它時都會產生不同的結果。為了防止這種情況，我們需要在將模型傳遞給 BERTopic 之前設置模型的 random_state。

因此，我們現在可以在每次運行模型時完全重現結果。

In [28]:
from umap import UMAP

umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)

## 3.3 控制 Topic 的數量

有一個參數來控制 Topic 的數量，即 nr_topics。但是，此參數會在創建主題後合併主題。它是一個支援創建固定數量主題的參數。

但是，建議通過集群模型控制主題的數量，默認情況下是 HDBSCAN。HDBSCAN 有一個參數，即 min_topic_size 間接控制將要創建的主題數量。

較高的 min_topic_size 將生成較少的主題，較低的 min_topic_size 將生成更多的主題。

在這裡，我們將使用 min_topic_size=40 來繞過 XXX 主題。

In [29]:
from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(min_cluster_size=150, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

In [30]:
from hdbscan import HDBSCAN
import numpy as np

from umap import UMAP

# 降到 5 維以內即可（通常 2~5）
reduced_embeddings = UMAP(n_components=5, random_state=42).fit_transform(embeddings)

for size in [50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400, 500, 1000]:
    clusterer = HDBSCAN(min_cluster_size=size, prediction_data=True)
    cluster_labels = clusterer.fit_predict(reduced_embeddings)

    n_clusters = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
    noise_ratio = np.mean(cluster_labels == -1)

    print(f"min_cluster_size={size}, n_clusters={n_clusters}, noise_ratio={noise_ratio:.2%}")

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=50, n_clusters=112, noise_ratio=47.51%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=75, n_clusters=72, noise_ratio=52.26%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=100, n_clusters=55, noise_ratio=56.97%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=125, n_clusters=44, noise_ratio=52.79%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=150, n_clusters=12, noise_ratio=7.86%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=175, n_clusters=7, noise_ratio=3.79%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=200, n_clusters=8, noise_ratio=12.41%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=225, n_clusters=8, noise_ratio=13.07%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=250, n_clusters=8, noise_ratio=12.26%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=275, n_clusters=4, noise_ratio=1.69%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=300, n_clusters=4, noise_ratio=1.69%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=325, n_clusters=4, noise_ratio=1.74%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=350, n_clusters=4, noise_ratio=1.75%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=375, n_clusters=3, noise_ratio=2.67%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=400, n_clusters=2, noise_ratio=1.94%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=500, n_clusters=2, noise_ratio=1.95%

C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\yoyo9\Desktop\114.06.18\bert_env\lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

min_cluster_size=1000, n_clusters=2, noise_ratio=79.03%

## 3.4 改進預設表示

主題的預設表示形式是通過 c-TF-IDF 計算的。但是，c-TF-IDF 由 CountVectorizer 提供支援，該 CountVectorizer 可將文本轉換為標記。使用 CountVectorizer，我們可以做很多事情：

- 刪除停用詞
- 忽略不常見的單詞
- 增加

換句話說，我們可以在將文檔分配給主題后預處理主題表示。這不會以任何方式影響聚類過程。

在這裡，我們將忽略英語停用詞和不常見的單詞。此外，通過增加 n-gram 範圍，我們將考慮由一個或兩個單詞組成的主題表示。

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer_model = CountVectorizer(stop_words="english", min_df=2, ngram_range=(1, 2))

## 3.5 其他表示

以前，我們已經調整了預設表示形式，但 BERTopic 中還有相當多的其他主題表示形式可供我們選擇。從 KeyBERTInspired 和 PartOfSpeech，到 OpenAI 的 ChatGPT 和開源替代品，許多表示都是可能的。

在 BERTopic 中，您可以同時對許多不同的主題表示進行建模，以測試它們並獲得主題描述的不同視角。這稱為多方面主題建模。

在這裡，我們將演示 BERTopic 中許多有趣且有用的表示形式：

- KeyBERT 啟發
    - 一種從 KeyBERT 工作原理中汲取靈感的方法
- 詞性
    - 使用 SpaCy 的 POS 標記提取單詞
- MaximalMarginalRelevance
    - 使主題詞多樣化
- 開放人工智慧
    - 使用 ChatGPT 標記我們的主題

In [62]:
import openai
from openai import OpenAI
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, OpenAI, PartOfSpeech

# KeyBERT
keybert_model = KeyBERTInspired()

# Part-of-Speech
pos_model = PartOfSpeech("en_core_web_sm")

# MMR
mmr_model = MaximalMarginalRelevance(diversity=0.3)

# gpt-4o-mini
prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]
The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short but highly descriptive topic label of at most 5 words. Make sure it is in the following format:
topic: <topic label>
"""
client = openai.OpenAI(api_key="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")
openai_model = OpenAI(client, model="gpt-4o-mini", exponential_backoff=True, chat=True, prompt=prompt)

# All representation models
representation_model = {
    "KeyBERT": keybert_model,
    "OpenAI": openai_model,
    "MMR": mmr_model,
    "POS": pos_model
}

# 4️⃣ 訓練

現在，我們有了一組最佳實踐，可以在訓練迴圈中使用它們。在這裡，將為我們的主題創建幾種不同的表示、關鍵字和標籤。如果要反覆運算主題模型，建議使用預先計算的嵌入，因為這可以顯著加快訓練速度。

## 4.1 訓練

In [63]:
from bertopic import BERTopic

# 架構
topic_model = BERTopic(

  # Pipeline models
  embedding_model=embedding_model,
  umap_model=umap_model,
  hdbscan_model=hdbscan_model,
  vectorizer_model=vectorizer_model,
  representation_model=representation_model,

  # Hyperparameters
  top_n_words=10,
  verbose=True
)

# 訓練
topics, probs = topic_model.fit_transform(sentences, embeddings)

2025-06-20 02:06:32,343 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-20 02:07:48,372 - BERTopic - Dimensionality - Completed ✓
2025-06-20 02:07:48,376 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-20 02:07:55,340 - BERTopic - Cluster - Completed ✓
2025-06-20 02:07:55,357 - BERTopic - Representation - Fine-tuning topics using representation models.
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:32<00:00,  1.23it/s]
2025-06-20 02:08:42,340 - BERTopic - Representation - Completed ✓

## 4.2 訓練結果

In [64]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,KeyBERT,OpenAI,MMR,POS,Representative_Docs
0,-1,19034,-1_new_like_car_នប,"[new, like, car, នប, just, នប នប, let, right, ...","[let, course, going, yeah, great, just, ll, do...",[Car Subscription and Entertainment Options],"[new, like, car, នប នប, look, great, performan...","[new, car, right, driving, look, time, great, ...","[Let's do it., The app is a Platinum Plan tria..."
1,0,4026,0_electric_charging_battery_engine,"[electric, charging, battery, engine, charge, ...","[electric car, electric vehicle, electric moto...",[Electric Vehicle Power Systems],"[electric, charging, hybrid, horsepower, ev, w...","[electric, battery, engine, charge, hybrid, po...","[The electric motor., By the way, fast chargin..."
2,1,2677,1_car_cars_vehicle_driving,"[car, cars, vehicle, driving, drive, vehicles,...","[car car, car like, automobile, drive car, car...",[Car Design and Experience],"[cars, driving, vehicles, sedan, new, car car,...","[car, cars, vehicle, driving, vehicles, sedan,...","[That car is nothing else than ., It's about t..."
3,2,1474,2_display_screen_navigation_phone,"[display, screen, navigation, phone, inch, sma...","[navigation, screen, screens, displays, displa...",[Advanced Vehicle Display Systems],"[screen, navigation, smartphone, button, andro...","[display, screen, navigation, phone, inch, sma...","[Through the multi-information display, the av..."
4,3,920,3_seats_seat_cargo_space,"[seats, seat, cargo, space, rear, rear seats, ...","[seats, rear seats, passenger seat, seats avai...",[Seating and Cargo Space Features],"[seats, cargo, rear seats, trunk, seating, pas...","[seats, seat, cargo, space, rear, rear seats, ...","[The rear seats are all of the same., Well, wh..."
5,4,751,4_das_die_en_wir,"[das, die, en, wir, der, la, dan, een, yang, det]","[einen, das, einem, auf, der, zuffenhausen, ko...",[Innovations in Automotive Development],"[das, der, det, auto, als, van, vi, auf, il, e...","[die, der, een, auto, du, als, man, einen, op,...","[Die Entwicklung hat sich insofern verändert, ..."
6,5,684,5_brand_customers_products_market,"[brand, customers, products, market, product, ...","[customers want, customers, consumers, custome...",[Sustainable Brand Growth Strategy],"[brand, customers, market, sales, new products...","[brand, customers, products, market, product, ...",[While protecting the value of our brand and o...
7,6,679,6_led_light_grille_lights,"[led, light, grille, lights, headlights, light...","[led headlights, headlights, led headlamps, le...",[Adaptive LED Headlight Design],"[headlights, lighting, led headlights, headlam...","[light, grille, lights, headlights, lighting, ...",[Pixel-inspired lighting signature with LED he...
8,7,631,7_thank thank_thank_thank guys_guys thank,"[thank thank, thank, thank guys, guys thank, g...","[thank, thank thank, thank guys, guys thank, ,...",[Expressions of Gratitude],"[thank thank, thank, thank guys, guys thank, g...","[guys, , , , , , , , , ]","[Thank you., Thank you., Thank you.]"
9,8,599,8_different_did_doing_lot,"[different, did, doing, lot, ve, new, change, ...","[things going, going doing, doing, approach, w...",[Embracing Change and Progress],"[different, did, change, challenge, things, fo...","[different, lot, new, challenge, things, peopl...","[And we're doing it the way., We're going to b..."
10,9,547,9_president_vice_welcome_vice president,"[president, vice, welcome, vice president, hi,...","[vice chairman, executive vice, vice president...",[Executive Leadership Introductions],"[president, vice, vice president, hi, ceo, gen...","[president, vice, gentlemen, ladies, manager, ...",[Please welcome Group Vice President and Gener...
11,10,490,10_design_designers_modern_beautiful,"[design, designers, modern, beautiful, know, s...","[design great, good design, new design, import...",[Innovative Design Concepts and Excellence],"[designers, sculpture, design team, expressive...","[design, designers, modern, beautiful, sculptu...","[It's a great design., It is a great design, a..."
12,11,436,11_air_climate_temperature_rear,"[air, climate, temperature, rear, cold, climat...","[airflow, air flow, air, air conditioning, ven...",[Advanced Climate Control Systems],"[temperature, climate control, cooling, dramat...","[air, climate, temperature, rear, cold, hot, c...",[It will circulate through the outside air in....
13,12,417,12_assist_lane_collision_braking,"[assist, lane, collision, braking, cruise, eme...","[driving assist, lane assist, safety features,...",[Advanced Driver Assistance Systems],"[assist, lane, cruise control, emergency braki...","[assist, lane, collision, braking, cruise, eme...",[These include forward collision avoidance ass...
14,13,326,13_interior_exterior_interior interior_interio...,"[interior, exterior, interior interior, interi...","[interior interior, look interior, interior, i...",[Interior Design and Space Experience],"[interior interior, interior design, look inte...","[interior, exterior, interior design, inside, ...","[And the interior as well., And, you can also ..."
15,14,315,14_steering_steering wheel_wheel_braking,"[steering, steering wheel, wheel, braking, bra...","[steering, steering wheel, steering feel, wrap...",[Steering and Driving Dynamics],"[steering, steering wheel, steering feel, rege...","[steering, wheel, braking, brake, pedal, rear,...","[The steering., They do move with the steering..."
16,15,305,15_yeah yeah_yeah_yep_sorry yeah,"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[yeah, yeah yeah, yep, , , , , , , ]",[Casual Affirmations and Apologies],"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[sorry, , , , , , , , , ]","[Yeah., Yeah., Yeah.]"
17,16,298,16_son___,"[son, , , , , , , , , ]","[, , , , , , , , , ]",[Relationship with Son],"[son, , , , , , , , , , , , , , , , , , , , , ...","[, , , , , , , , , ]","[., ., Son.]"
18,17,279,17_okay_okay okay_absolutely_sure,"[okay, okay okay, absolutely, sure, alright, s...","[okay, ok, okay okay, alright, okay yeah, yeah...",[Affirmative Responses and Agreement],"[alright alright, absolutely yeah, fine fine, ...","[sure, unreal, cool, folks, stuff, great, , , , ]","[Okay., Okay., Okay.]"
19,18,272,18_ioniq_life important_smartsense_charging,"[ioniq, life important, smartsense, charging, ...","[ioniq, ioniq limited, ioniq hybrid, vehicle i...",[IONIQ Electric Vehicle Features],"[ioniq, life important, smartsense, charging, ...","[charging, platform, life, electric, important...","[is a very important part of the IONIQ life., ..."
20,19,257,19_s60_xc40_xc90_xc40 recharge,"[s60, xc40, xc90, xc40 recharge, recharge, new...","[xc40 recharge, xc40, recharge, xc60, xc90, el...",[XC40 Recharge Electric Support Technology],"[s60, xc40, xc90, xc40 recharge, new s60, s90,...","[recharge, new, safety, cars, experience, car,...",[We're not going to connect with the XC40 Rech...
21,20,256,20_cool_nice_amazing_pretty,"[cool, nice, amazing, pretty, really, awesome,...","[really cool, looks cool, great cool, pretty c...",[Expressions of Enthusiastic Approval],"[pretty, really cool, pretty cool, just incred...","[cool, nice, amazing, awesome, incredible, gre...","[It's that cool., So it looks really cool., It..."
22,21,254,21_prius_prius prime_prime_hybrid,"[prius, prius prime, prime, hybrid, efficiency...","[prius, new prius, prius prime, hybrid prius, ...",[Prius Hybrid Vehicle Overview],"[prius, prius prime, hybrid, new prius, safety...","[hybrid, efficiency, family, safety, drive, pl...","[Prius., Prius., Prius.]"
23,22,239,22_thank_joining_today_thank joining,"[thank, joining, today, thank joining, thanks,...","[thank joining, thanks joining, joining today,...",[Gratitude for Joining Event],"[thank joining, thank time, today thank, joini...","[today, thanks, welcome, attention, day, gentl...","[Thank you for joining us., Thank you for join..."
24,23,211,23_class_new class_new_minivan,"[class, new class, new, minivan, mercedes, ass...","[class, class thing, class course, class level...",[Mercedes Luxury Class Vehicles],"[class, new class, minivan, mercedes, driving ...","[class, new, minivan, assistance, driving, sys...","[The C-Class., In its class., The S-Class.]"
25,24,208,24_nsx_nx_crossover_supercar,"[nsx, nx, crossover, supercar, new, cx, cx 30,...","[nsx, nx, rx, cx, new generation, cx 30, ux, g...",[Next-Gen NSX Supercar Evolution],"[nsx, nx, supercar, cx, cx 30, engine, electri...","[crossover, supercar, new, performance, genera...","[It's a new generation of the NSX., To me the ..."
26,25,208,25_auto_la_los_los angeles,"[auto, la, los, los angeles, angeles, detroit,...","[los angeles, angeles, la auto, la, right la, ...",[2015 Los Angeles Auto Show],"[los angeles, detroit, toronto, la auto, inter...","[auto, beach, international, season, city, wel...","[We started with you in Los Angeles, went to D..."
27,26,195,26_color_colors_blue_tone,"[color, colors, blue, tone, red, black, exteri...","[different colors, colour, colors, blue, color...",[Protonic Blue Color Options],"[color, colors, exterior colors, new color, co...","[color, colors, blue, tone, red, black, exteri...","[And this color?, And the color?, Our color co..."
28,27,189,27_elantra_elr_new elantra_elantra hybrid,"[elantra, elr, new elantra, elantra hybrid, ne...","[elantra, new elantra, 2017 elantra, elantra l...",[Elantra Safety and Features Overview],"[elantra, elr, new elantra, elantra hybrid, 20...","[elantra, new, safety, generation, features, h...","[And I'm going to be back with Elantra., Well,..."
29,28,189,28_rav4_rav4 prime_prime_hybrid,"[rav4, rav4 prime, prime, hybrid, road, trd, a...","[rav4 prime, new rav4, rav4, rav4 hybrid, 2023...",[RAV4 Prime Features and Performance],"[rav4 prime, trd road, plug hybrid, rav4 hybri...","[hybrid, road, available, plug, grades, grade,...","[On top of all that, RAV4 Prime is also highly..."
30,29,186,29_technology_technologies_tech_innovation,"[technology, technologies, tech, innovation, a...","[technology, new technology, technology new, t...",[Innovations in Advanced Technology],"[technologies, tech, innovation, lot technolog...","[technology, technologies, tech, innovation, a...","[I've always been into technology., Technology..."
31,30,175,30_camry_toyota_toyota com_com,"[camry, toyota, toyota com, com, trd, new camr...","[camry camry, camry, new camry, camry features...",[Toyota Camry Features and Offerings],"[toyota, toyota com, trd, new camry, slash, ca...","[camry, visit, grades, drive, available, new, ...","[Well, that's more than the Camry., I own a Ca..."
32,31,174,31_wheels_inch_alloy_alloy wheels,"[wheels, inch, alloy, alloy wheels, 20 inch, i...","[alloy wheels, inch wheels, alloy wheel, wheel...",[Alloy Wheel Sizes and Designs],"[wheels, alloy wheels, 20 inch, inch alloy, in...","[wheels, inch, alloy, black, tires, wheel, inc...","[Or 19 inch alloy wheels on the rear., 20-inch..."
33,32,173,32_corolla_corolla hybrid_new corolla_hybrid,"[corolla, corolla hybrid, new corolla, hybrid,...","[corolla hybrid, new corolla, corolla, corolla...",[Corolla Hybrid and Features],"[corolla, corolla hybrid, new corolla, corolla...","[hybrid, safety, new, grades, modern, lineup, ...",[It's a unique choice for both the Corolla and...
34,33,169,33_sonata_2018 sonata_new sonata_2018,"[sonata, 2018 sonata, new sonata, 2018, sonata...","[2018 sonata, new sonata, sonata, sonata comes...",[2018 Sonata Features and Technology],"[sonata, 2018 sonata, new sonata, sonata hybri...","[liter, turbo, safety, engine, hybrid, new, fe...","[The 2018 Sonata, our best Sonata ever., So th..."
35,34,168,34_oh_oh oh_uh_huh,"[oh, oh oh, uh, huh, hmm, mm, oh yeah, kidding...","[oh, oh oh, oh yeah, ah, um, yeah oh, uh, oh m...",[Expressions of Surprise and Reaction],"[whoa, yaw, boom, yeah oh, ooh ooh, excuse, li...","[hmm, , , , , , , , , ]","[Oh., Oh., Oh.]"
36,35,160,35_eqs_eqe_eq_mercedes,"[eqs, eqe, eq, mercedes, mercedes eq, new eqs,...","[new eqs, eqs comes, new eqe, eqs, eqe comes, ...",[Mercedes EQS Electric Vehicles],"[eqs, mercedes eq, new eqs, new eqe, eq boost,...","[new, electric, boost, driving, family, design...","[And the new EQS is no different., I'm about t..."
37,36,157,36_mustang_mach_mustang mach_really,"[mustang, mach, mustang mach, really, know, id...","[mustang, know mustang, electric mustang, must...",[Mustang Electric Vehicle Excitement],"[mustang, mach, mustang mach, iconic, look lik...","[iconic, team, vehicle, customers, excited, lo...","[Do we call it a Mustang?, My Mustang is every..."
38,37,153,37_bye_bye bye_goodbye_say goodbye,"[bye, bye bye, goodbye, say goodbye, say, time...","[bye bye, bye, goodbye, say goodbye, leave, sa...",[Farewells and Goodbyes],"[bye, bye bye, goodbye, say goodbye, time say,...","[bye, goodbye, mate, note, work, today, time, ...","[Bye-bye., Bye-bye for now., Bye-bye.]"
39,38,152,38_highlander_grand highlander_grand_suv,"[highlander, grand highlander, grand, suv, hig...","[grand highlander, highlander exterior, highla...",[Grand Highlander Interior and Exterior],"[highlander, grand highlander, suv, highlander...","[standard, exterior, available, grades, end, w...",[That's what makes Grand Highlander's exterior...

## 4.3 獲取單個主題的所有表示形式

In [65]:
topic_model.get_topic(1, full=True)

{'Main': [('car', 0.06464488811766111),
  ('cars', 0.03132104705250897),
  ('vehicle', 0.02326203891591233),
  ('driving', 0.02109589395940831),
  ('drive', 0.02068884023046331),
  ('vehicles', 0.013880411345292294),
  ('really', 0.013118748188451084),
  ('sedan', 0.012629669295603885),
  ('just', 0.012367317148721956),
  ('new', 0.011868936110531617)],
 'KeyBERT': [('car car', 0.7048411),
  ('car like', 0.6854874),
  ('automobile', 0.6446377),
  ('drive car', 0.6432355),
  ('car', 0.6419177),
  ('car really', 0.6354376),
  ('important car', 0.63482565),
  ('vehicle', 0.6332723),
  ('car just', 0.59300196),
  ('new car', 0.5841867)],
 'OpenAI': [('Car Design and Experience', 1)],
 'MMR': [('cars', 0.03132104705250897),
  ('driving', 0.02109589395940831),
  ('vehicles', 0.013880411345292294),
  ('sedan', 0.012629669295603885),
  ('new', 0.011868936110531617),
  ('car car', 0.010568316630699624),
  ('design', 0.010153531974244099),
  ('road', 0.010075788416339153),
  ('experience', 0.00977417129310274),
  ('suv', 0.009371227681212305)],
 'POS': [('car', 0.06464488811766111),
  ('cars', 0.03132104705250897),
  ('vehicle', 0.02326203891591233),
  ('driving', 0.02109589395940831),
  ('vehicles', 0.013880411345292294),
  ('sedan', 0.012629669295603885),
  ('new', 0.011868936110531617),
  ('driver', 0.010755985064837936),
  ('great', 0.010552498899502404),
  ('design', 0.010153531974244099)]}

# 5️⃣ 設定標籤

每個主題的預設標籤是每個主題中的前3個單詞加上它們之間的下劃線。

當然，這可能不是您能想到的某個主題的最佳標籤。相反，我們可以使用 .set_topic_labels 手動標記所有或某些主題。

我們還可以使用 .set_topic_labels 來使用我們之前的其他主題表示形式之一，例如 KeyBERTInspired 甚至 OpenAI。

## 5.1 手動設定主題名稱

In [54]:
topic_model.set_topic_labels({0: "design", 1: "drive", 2: "display_screen", 3: "charging_battery", 4: "seats"})

### 檢視

In [55]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,KeyBERT,OpenAI,MMR,POS,Representative_Docs
0,-1,19774,-1_car_like_new_just,Outlier Topic,"[car, like, new, just, right, really, let, goi...","[premium, miles, toyota, plus, car, years, gre...",[Enhanced Car Experience Features],"[like, new, driving, vehicle, time, rear, rang...","[car, new, right, driving, great, look, vehicl...","[Plus, there's a standard three-month SiriusXM..."
1,0,2273,0_car_cars_vehicle_drive,design,"[car, cars, vehicle, drive, driving, really, v...","[car car, car like, car really, car, know car,...",[High-Performance Vehicle Experience],"[car, cars, driving, vehicles, car car, ford, ...","[car, cars, vehicle, driving, vehicles, new, d...",[And the car I'm about to show you is one of t...
2,1,1611,1_electric_engine_horsepower_hybrid,drive,"[electric, engine, horsepower, hybrid, torque,...","[engine power, v6 engine, electric car, electr...",[Advanced Powertrain Technologies],"[horsepower, liter, electric motor, powertrain...","[electric, engine, horsepower, hybrid, torque,...",[This plug-in hybrid EV powertrain couples a 2...
3,2,1258,2_display_screen_navigation_phone,display_screen,"[display, screen, navigation, phone, inch, but...","[apple carplay, carplay android, smartphone, a...",[Advanced Vehicle Display Technology],"[navigation, android, smartphone, touchscreen,...","[display, screen, navigation, phone, inch, but...",[You can pair it with the Apple CarPlay or And...
4,3,1042,3_seats_seat_space_cargo,charging_battery,"[seats, seat, space, cargo, rear, rear seats, ...","[seats, seats available, seating, seat, rear s...",[Rear Seat and Cargo Space],"[seats, cargo, rear seats, trunk, passengers, ...","[seats, seat, space, cargo, rear, rear seats, ...","[Well, what about the seats?, Please take your..."
5,4,751,4_customers_products_product_market,seats,"[customers, products, product, market, custome...","[new products, new product, products, marketin...",[Creative Leadership in Design],"[customers, market, brand, sales, industry, ne...","[customers, products, product, market, custome...","[In my industry, when we do commercial for TV ..."
6,5,705,5_thank thank_thank_thanks_thanks thanks,Expressions of Gratitude,"[thank thank, thank, thanks, thanks thanks, th...","[thank, thanks, thank thanks, thank thank, tha...",[Expressions of Gratitude],"[thanks thank, thank congratulations, thanks l...","[thanks, lot, man, guys, dude, stokin, donuts,...","[Thank you., Thank you., Thank you.]"
7,6,700,6_នប_នប នប_av_nicolai,Multilingual Text and Navigation,"[នប, នប នប, av, nicolai, nicolai winther, wint...","[av nicolai, nicolai, nicolai winther, tekstin...",[Multilingual Text and Navigation],"[នប នប, nicolai, nicolai winther, av nicolai, ...","[die, auto, du, als, auf, man, wird, har, rod,...",[Teksting av Nicolai Winther Teksting av Nicol...
8,7,650,7_time_forward_different_going,Embracing Change in Research Practices,"[time, forward, different, going, lot, want, d...","[looking forward, time forward, ahead, hope, g...",[Embracing Change in Research Practices],"[did, like, things, challenge, research, step,...","[time, different, lot, things, way, people, ch...","[Now, to get there, the way we do research is ..."
9,8,649,8_bmw_series_new bmw_i8,BMW Series Overview and Models,"[bmw, series, new bmw, i8, bmw series, i3, new...","[bmw bmw, new bmw, car bmw, bmw, bmw i7, bmw s...",[BMW Series Overview and Models],"[new bmw, bmw series, bmw i3, charging, bmw i8...","[series, i8, i3, new, touring, charging, vehic...",[for you to individualise your new BMW 5-Serie...
10,9,531,9_led_light_headlights_lights,LED Exterior Lighting Features,"[led, light, headlights, lights, lighting, led...","[led headlights, led taillights, headlights, l...",[LED Exterior Lighting Features],"[headlights, lights, led headlights, headlight...","[light, headlights, lights, lighting, lamps, t...","[Plus, the Apex Edition also features standard..."
11,10,499,10_design_designers_designer_really,Innovative and Exceptional Design,"[design, designers, designer, really, sculptur...","[design great, good design, important design, ...",[Innovative and Exceptional Design],"[designers, designer, sculpture, modern, new d...","[design, designers, sculpture, modern, beautif...","[It's an amazing design., I think it's the des..."
12,11,487,11_charging_charge_stations_charging stations,Electric Vehicle Charging Stations,"[charging, charge, stations, charging stations...","[charging stations, charging station, charging...",[Electric Vehicle Charging Stations],"[charging stations, charger, charging station,...","[charging, charge, stations, level, home, fast...","[So I see all the charging stations here., Whe..."
13,12,476,12_hyundai_sonata_elantra_នប,2018 Hyundai Sonata Highlights,"[hyundai, sonata, elantra, នប, នប នប, hyundai ...","[hyundai sonata, hyundai, new hyundai, hyundai...",[2018 Hyundai Sonata Highlights],"[hyundai, sonata, hyundai sonata, new elantra,...","[hyundai, elantra, new, safety, brand, best, h...","[The 2018 Hyundai Sonata., The 2018 Hyundai So..."
14,13,438,13_kia_ev6_ev_bolt,Kia EV6 Electric Vehicle Launch,"[kia, ev6, ev, bolt, evs, kia ev6, bolt ev, ev...","[kia ev6, ev6, new kia, kia, kia motors, ev6 g...",[Kia EV6 Electric Vehicle Launch],"[kia, ev6, ev, kia ev6, bolt ev, ev6 gt, new k...","[bolt, new, electric, customers, year, industr...","[The debut of the all-electric Kia EV6., Kia E..."
15,14,421,14_lexus_nx_nsx_acura,Lexus NX Innovative Features,"[lexus, nx, nsx, acura, new, es, brand, luxury...","[lexus, lexus inform, lexus safety, rx, nsx, i...",[Lexus NX Innovative Features],"[lexus, nsx, acura, ilx, hybrid, cx, cx 30, sa...","[new, brand, luxury, safety, generation, perfo...",[of available sources including your streaming...
16,15,385,15_steering_steering wheel_wheel_brake,Steering Control and Feedback,"[steering, steering wheel, wheel, brake, pedal...","[steering, steering wheel, steering feel, hand...",[Steering Control and Feedback],"[steering, steering wheel, regenerative brakin...","[steering, wheel, brake, pedal, braking, rear,...","[The steering., With recalibrated steering., I..."
17,16,378,16_volvo_s60_xc40_xc90,New Volvo S60 Overview,"[volvo, s60, xc40, xc90, recharge, ex90, new, ...","[volvo car, volvo, volvo cars, volvo xc40, new...",[New Volvo S60 Overview],"[volvo, xc40, recharge, ex90, volvo cars, new ...","[recharge, new, safety, cars, car, design, saf...","[It's still a Volvo., This is the all-new Volv..."
18,17,374,17_thank_hi_chris_hey,Gratitude and Greetings Messages,"[thank, hi, chris, hey, jesse, thanks, brian, ...","[jim thank, thank mr, thank, thanks, welcome, ...",[Gratitude and Greetings Messages],"[hi, chris, jesse, matthias, mike, andy, ron, ...","[thanks, question, welcome, ado, explanation, ...","[Thank you, Troy., Thank you, Naomi., Thank yo..."
19,18,361,18_assist_lane_collision_cruise,Advanced Driver Assistance Systems,"[assist, lane, collision, cruise, braking, ale...","[driving assist, lane assist, alert steering, ...",[Advanced Driver Assistance Systems],"[assist, cruise control, blind spot, cross tra...","[assist, lane, collision, cruise, braking, ale...",[Enhancing systems like its Pre-Collision Syst...
20,19,339,19_audi_tron_q8_a4,Audi Electric Vehicle Innovations,"[audi, tron, q8, a4, audi tron, a7, q8 tron, q...","[audi audi, audi, new audi, 2019 audi, audi a4...",[Audi Electric Vehicle Innovations],"[audi tron, q8 tron, a6, suv, 2019 audi, new a...","[tron, new, design, electric, car, systems, li...",[This car should have something which no other...
21,20,319,20_rav4_highlander_rav4 prime_prime,2023 Toyota RAV4 Prime Features,"[rav4, highlander, rav4 prime, prime, hybrid, ...","[rav4 hybrid, rav4 prime, new rav4, rav4, rav4...",[2023 Toyota RAV4 Prime Features],"[rav4 prime, grand highlander, toyota, suv, st...","[highlander, hybrid, road, available, grades, ...","[On top of all that, RAV4 Prime is also highly..."
22,21,301,21_yeah yeah_yeah_yep_dude,Affirmative Expressions and Slang,"[yeah yeah, yeah, yep, dude, , , , , , ]","[yeah, yeah yeah, yep, , , , , , , ]",[Affirmative Expressions and Slang],"[yeah yeah, yeah, yep, dude, , , , , , , , , ,...","[, , , , , , , , , ]","[Yeah., Yeah., Yeah.]"
23,22,275,22_interior_exterior_interior interior_interio...,Interior Design and Experience,"[interior, exterior, interior interior, interi...","[interior interior, interior, interior just, l...",[Interior Design and Experience],"[interior, interior interior, interior design,...","[interior, exterior, interior design, design, ...","[And we find it also here in the interior., An..."
24,23,274,23_class_mercedes_benz_mercedes benz,Luxury Mercedes-Benz S-Class,"[class, mercedes, benz, mercedes benz, new cla...","[class, class level, class best, class class, ...",[Luxury Mercedes-Benz S-Class],"[mercedes benz, new mercedes, benz class, clas...","[class, new, car, world, luxury, digital, assi...","[The S-Class., The S-Class., The S-Class.]"
25,24,272,24_son_mr__,Family Dynamics and Relationships,"[son, mr, , , , , , , , ]","[, , , , , , , , , ]",[Family Dynamics and Relationships],"[son, mr, , , , , , , , , , , , , , , , , , , ...","[, , , , , , , , , ]","[., Mr., Son.]"
26,25,271,25_nissan_leaf_nissan leaf_ariya,Nissan Leaf Launch and Technology,"[nissan, leaf, nissan leaf, ariya, new nissan,...","[nissan leaf, nissan intelligent, new nissan, ...",[Nissan Leaf Launch and Technology],"[nissan, nissan leaf, ariya, new nissan, nissa...","[leaf, intelligent mobility, intelligent, new,...","[The new LEAF is the future of Nissan., The ne..."
27,26,265,26_okay_okay okay_sure_nice,Positive Affirmations and Responses,"[okay, okay okay, sure, nice, awesome, okay su...","[okay, ok, okay okay, alright, okay yeah, yeah...",[Positive Affirmations and Responses],"[sure sure, awesome awesome, nice nice, alrigh...","[sure, nice, awesome, cool, , , , , , ]","[Okay., Okay., Okay.]"
28,27,255,27_ioniq_hyundai_hyundai ioniq_charging,Hyundai IONIQ Electric Vehicles,"[ioniq, hyundai, hyundai ioniq, charging, plat...","[hyundai ioniq, vehicle ioniq, ioniq, ioniq li...",[Hyundai IONIQ Electric Vehicles],"[ioniq, hyundai, hyundai ioniq, charging, ioni...","[charging, platform, life, important, electric...",[Hyundai is a very important part of the IONIQ...
29,28,253,28_prius_prius prime_prime_toyota,Toyota Prius Hybrid Efficiency,"[prius, prius prime, prime, toyota, hybrid, ef...","[prius, new prius, prius prime, prius limited,...",[Toyota Prius Hybrid Efficiency],"[prius, prius prime, toyota, hybrid, new prius...","[hybrid, efficiency, family, safety, grades, d...","[Prius., Prius., Prius.]"
30,29,244,29_cool_amazing_nice_pretty,Expressions of Coolness and Awe,"[cool, amazing, nice, pretty, awesome, really,...","[really cool, pretty cool, cool, awesome cool,...",[Expressions of Coolness and Awe],"[pretty, really cool, amazing really, really n...","[cool, amazing, nice, awesome, fantastic, grea...","[How cool is that?, Very cool., So cool.]"
31,30,236,30_air_climate_temperature_cold,Climate Control Systems Overview,"[air, climate, temperature, cold, climate cont...","[automatic climate, climate control, climate c...",[Climate Control Systems Overview],"[temperature, climate control, musikk dramatis...","[air, climate, temperature, cold, hot, musikk,...",[Step inside and enjoy the standard three-zone...
32,31,218,31_thank_joining_today_thank joining,Appreciation for Joining Event,"[thank, joining, today, thank joining, thanks,...","[thank joining, thanks joining, joining today,...",[Appreciation for Joining Event],"[thank joining, thank time, today thank, joini...","[today, thanks, day, time, happy, rest, mornin...","[Thank you all for joining us., Thank you for ..."
33,32,204,32_battery_pack_battery pack_batteries,Battery Technology and Management,"[battery, pack, battery pack, batteries, lithi...","[battery, better battery, battery pack, batter...",[Battery Technology and Management],"[battery pack, batteries, lithium ion, floor, ...","[battery, pack, batteries, lithium, cells, ion...","[The battery., It's all about the battery., It..."
34,33,196,33_polestar_öhlins_brand_volvo,Polestar Electric Performance Cars,"[polestar, öhlins, brand, volvo, electric, pol...","[polestar, polestar really, polestar brand, wo...",[Polestar Electric Performance Cars],"[polestar, öhlins, volvo, electric, polestar b...","[brand, electric, car, electric car, customer,...","[That is the Polestar., This is Polestar 1., P..."
35,34,185,34_color_colors_blue_black,Color Options for Exterior Automotive,"[color, colors, blue, black, tone, exterior, o...","[different colors, colors, colour, colors avai...",[Color Options for Exterior Automotive],"[colors, exterior colors, silver, colour, blue...","[color, colors, blue, black, tone, exterior, o...","[And the color?, Our color combination is call..."
36,35,184,35_wheels_inch_alloy_alloy wheels,Alloy Wheel Sizes and Designs,"[wheels, inch, alloy, alloy wheels, 20 inch, i...","[alloy wheels, alloy wheel, inch wheels, wheel...",[Alloy Wheel Sizes and Designs],"[wheels, alloy wheels, 19, inch wheels, tires,...","[wheels, inch, alloy, black, tires, spoke, whe...","[Or 19 inch alloy wheels on the rear., You hav..."
37,36,181,36_sound_noise_quiet_hear,Sound and Acoustics Exploration,"[sound, noise, quiet, hear, acoustic, silent, ...","[sound, sound actually, sound hear, sound expe...",[Sound and Acoustics Exploration],"[noise, acoustic, quietness, whisper, wind noi...","[sound, noise, quiet, acoustic, silent, silenc...","[There's no sound, no audio., Sound., The Burm..."
38,37,169,37_president_vice_vice president_ceo,Automotive Executive Introductions,"[president, vice, vice president, ceo, welcome...","[vice chairman, welcome vice, lexus, vice pres...",[Automotive Executive Introductions],"[vice, vice president, ceo, gentlemen welcome,...","[president, vice, manager, chief, gentlemen, e...","[Ladies and gentlemen, please welcome Group Vi..."
39,38,162,38_corolla_corolla hybrid_new corolla_hybrid,New Toyota Corolla Hybrid Release,"[corolla, corolla hybrid, new corolla, hybrid,...","[corolla hybrid, new corolla, corolla, toyota ...",[New Toyota Corolla Hybrid Release],"[corolla, corolla hybrid, new corolla, corolla...","[hybrid, new, grades, safety, modern, lineup, ...","[We have US's first ever Corolla Hybrid., It's..."
40,39,159,39_miles_hour_miles hour_range,Speed and Range Performance,"[miles, hour, miles hour, range, kilometers, 1...","[100 miles, miles hour, 65 miles, 80 mile, 70 ...",[Speed and Range Performance],"[miles hour, 100 miles, quarter mile, kilomete...","[miles, hour, range, kilometers, mile, seconds...",[Driving at speeds in excess of 70 miles per h...
41,40,154,40_eqs_eqe_eq_mercedes,Mercedes EQ Electric Vehicles,"[eqs, eqe, eq, mercedes, mercedes eq, new eqs,...","[new eqs, eqs comes, new eqe, eqs, eqe comes, ...",[Mercedes EQ Electric Vehicles],"[eqs, mercedes eq, new eqs, new mercedes, eqs ...","[new, electric, boost, driving, design, electr...","[And the new EQS is no different., 🎵 🎵 🎵 🎵 🎵 🎵..."
42,41,154,41_bye_bye bye_goodbye_say goodbye,Farewells and Goodbyes,"[bye, bye bye, goodbye, say goodbye, say, time...","[bye bye, bye, goodbye, say goodbye, leave, sa...",[Farewells and Goodbyes],"[bye, bye bye, goodbye, say goodbye, time say,...","[bye, goodbye, mate, note, work, today, time, ...","[Bye-bye., Bye-bye., Bye bye.]"

### 輸出存檔

In [ ]:
topic_info = topic_model.get_topic_info()
topic_info.to_csv("topic_info.csv", index=False, encoding="utf-8-sig")

## 5.2 KeyBERTInspired設定系統名稱

In [66]:
keybert_topic_labels = {topic: " | ".join(list(zip(*values))[0][:3]) for topic, values in topic_model.topic_aspects_["KeyBERT"].items()}
topic_model.set_topic_labels(keybert_topic_labels)

### 檢視

In [67]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,KeyBERT,OpenAI,MMR,POS,Representative_Docs
0,-1,19034,-1_new_like_car_នប,let | course | going,"[new, like, car, នប, just, នប នប, let, right, ...","[let, course, going, yeah, great, just, ll, do...",[Car Subscription and Entertainment Options],"[new, like, car, នប នប, look, great, performan...","[new, car, right, driving, look, time, great, ...","[Let's do it., The app is a Platinum Plan tria..."
1,0,4026,0_electric_charging_battery_engine,electric car | electric vehicle | electric motor,"[electric, charging, battery, engine, charge, ...","[electric car, electric vehicle, electric moto...",[Electric Vehicle Power Systems],"[electric, charging, hybrid, horsepower, ev, w...","[electric, battery, engine, charge, hybrid, po...","[The electric motor., By the way, fast chargin..."
2,1,2677,1_car_cars_vehicle_driving,car car | car like | automobile,"[car, cars, vehicle, driving, drive, vehicles,...","[car car, car like, automobile, drive car, car...",[Car Design and Experience],"[cars, driving, vehicles, sedan, new, car car,...","[car, cars, vehicle, driving, vehicles, sedan,...","[That car is nothing else than ., It's about t..."
3,2,1474,2_display_screen_navigation_phone,navigation | screen | screens,"[display, screen, navigation, phone, inch, sma...","[navigation, screen, screens, displays, displa...",[Advanced Vehicle Display Systems],"[screen, navigation, smartphone, button, andro...","[display, screen, navigation, phone, inch, sma...","[Through the multi-information display, the av..."
4,3,920,3_seats_seat_cargo_space,seats | rear seats | passenger seat,"[seats, seat, cargo, space, rear, rear seats, ...","[seats, rear seats, passenger seat, seats avai...",[Seating and Cargo Space Features],"[seats, cargo, rear seats, trunk, seating, pas...","[seats, seat, cargo, space, rear, rear seats, ...","[The rear seats are all of the same., Well, wh..."
5,4,751,4_das_die_en_wir,einen | das | einem,"[das, die, en, wir, der, la, dan, een, yang, det]","[einen, das, einem, auf, der, zuffenhausen, ko...",[Innovations in Automotive Development],"[das, der, det, auto, als, van, vi, auf, il, e...","[die, der, een, auto, du, als, man, einen, op,...","[Die Entwicklung hat sich insofern verändert, ..."
6,5,684,5_brand_customers_products_market,customers want | customers | consumers,"[brand, customers, products, market, product, ...","[customers want, customers, consumers, custome...",[Sustainable Brand Growth Strategy],"[brand, customers, market, sales, new products...","[brand, customers, products, market, product, ...",[While protecting the value of our brand and o...
7,6,679,6_led_light_grille_lights,led headlights | headlights | led headlamps,"[led, light, grille, lights, headlights, light...","[led headlights, headlights, led headlamps, le...",[Adaptive LED Headlight Design],"[headlights, lighting, led headlights, headlam...","[light, grille, lights, headlights, lighting, ...",[Pixel-inspired lighting signature with LED he...
8,7,631,7_thank thank_thank_thank guys_guys thank,thank | thank thank | thank guys,"[thank thank, thank, thank guys, guys thank, g...","[thank, thank thank, thank guys, guys thank, ,...",[Expressions of Gratitude],"[thank thank, thank, thank guys, guys thank, g...","[guys, , , , , , , , , ]","[Thank you., Thank you., Thank you.]"
9,8,599,8_different_did_doing_lot,things going | going doing | doing,"[different, did, doing, lot, ve, new, change, ...","[things going, going doing, doing, approach, w...",[Embracing Change and Progress],"[different, did, change, challenge, things, fo...","[different, lot, new, challenge, things, peopl...","[And we're doing it the way., We're going to b..."
10,9,547,9_president_vice_welcome_vice president,vice chairman | executive vice | vice president,"[president, vice, welcome, vice president, hi,...","[vice chairman, executive vice, vice president...",[Executive Leadership Introductions],"[president, vice, vice president, hi, ceo, gen...","[president, vice, gentlemen, ladies, manager, ...",[Please welcome Group Vice President and Gener...
11,10,490,10_design_designers_modern_beautiful,design great | good design | new design,"[design, designers, modern, beautiful, know, s...","[design great, good design, new design, import...",[Innovative Design Concepts and Excellence],"[designers, sculpture, design team, expressive...","[design, designers, modern, beautiful, sculptu...","[It's a great design., It is a great design, a..."
12,11,436,11_air_climate_temperature_rear,airflow | air flow | air,"[air, climate, temperature, rear, cold, climat...","[airflow, air flow, air, air conditioning, ven...",[Advanced Climate Control Systems],"[temperature, climate control, cooling, dramat...","[air, climate, temperature, rear, cold, hot, c...",[It will circulate through the outside air in....
13,12,417,12_assist_lane_collision_braking,driving assist | lane assist | safety features,"[assist, lane, collision, braking, cruise, eme...","[driving assist, lane assist, safety features,...",[Advanced Driver Assistance Systems],"[assist, lane, cruise control, emergency braki...","[assist, lane, collision, braking, cruise, eme...",[These include forward collision avoidance ass...
14,13,326,13_interior_exterior_interior interior_interio...,interior interior | look interior | interior,"[interior, exterior, interior interior, interi...","[interior interior, look interior, interior, i...",[Interior Design and Space Experience],"[interior interior, interior design, look inte...","[interior, exterior, interior design, inside, ...","[And the interior as well., And, you can also ..."
15,14,315,14_steering_steering wheel_wheel_braking,steering | steering wheel | steering feel,"[steering, steering wheel, wheel, braking, bra...","[steering, steering wheel, steering feel, wrap...",[Steering and Driving Dynamics],"[steering, steering wheel, steering feel, rege...","[steering, wheel, braking, brake, pedal, rear,...","[The steering., They do move with the steering..."
16,15,305,15_yeah yeah_yeah_yep_sorry yeah,yeah | yeah yeah | yep,"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[yeah, yeah yeah, yep, , , , , , , ]",[Casual Affirmations and Apologies],"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[sorry, , , , , , , , , ]","[Yeah., Yeah., Yeah.]"
17,16,298,16_son___,| |,"[son, , , , , , , , , ]","[, , , , , , , , , ]",[Relationship with Son],"[son, , , , , , , , , , , , , , , , , , , , , ...","[, , , , , , , , , ]","[., ., Son.]"
18,17,279,17_okay_okay okay_absolutely_sure,okay | ok | okay okay,"[okay, okay okay, absolutely, sure, alright, s...","[okay, ok, okay okay, alright, okay yeah, yeah...",[Affirmative Responses and Agreement],"[alright alright, absolutely yeah, fine fine, ...","[sure, unreal, cool, folks, stuff, great, , , , ]","[Okay., Okay., Okay.]"
19,18,272,18_ioniq_life important_smartsense_charging,ioniq | ioniq limited | ioniq hybrid,"[ioniq, life important, smartsense, charging, ...","[ioniq, ioniq limited, ioniq hybrid, vehicle i...",[IONIQ Electric Vehicle Features],"[ioniq, life important, smartsense, charging, ...","[charging, platform, life, electric, important...","[is a very important part of the IONIQ life., ..."
20,19,257,19_s60_xc40_xc90_xc40 recharge,xc40 recharge | xc40 | recharge,"[s60, xc40, xc90, xc40 recharge, recharge, new...","[xc40 recharge, xc40, recharge, xc60, xc90, el...",[XC40 Recharge Electric Support Technology],"[s60, xc40, xc90, xc40 recharge, new s60, s90,...","[recharge, new, safety, cars, experience, car,...",[We're not going to connect with the XC40 Rech...
21,20,256,20_cool_nice_amazing_pretty,really cool | looks cool | great cool,"[cool, nice, amazing, pretty, really, awesome,...","[really cool, looks cool, great cool, pretty c...",[Expressions of Enthusiastic Approval],"[pretty, really cool, pretty cool, just incred...","[cool, nice, amazing, awesome, incredible, gre...","[It's that cool., So it looks really cool., It..."
22,21,254,21_prius_prius prime_prime_hybrid,prius | new prius | prius prime,"[prius, prius prime, prime, hybrid, efficiency...","[prius, new prius, prius prime, hybrid prius, ...",[Prius Hybrid Vehicle Overview],"[prius, prius prime, hybrid, new prius, safety...","[hybrid, efficiency, family, safety, drive, pl...","[Prius., Prius., Prius.]"
23,22,239,22_thank_joining_today_thank joining,thank joining | thanks joining | joining today,"[thank, joining, today, thank joining, thanks,...","[thank joining, thanks joining, joining today,...",[Gratitude for Joining Event],"[thank joining, thank time, today thank, joini...","[today, thanks, welcome, attention, day, gentl...","[Thank you for joining us., Thank you for join..."
24,23,211,23_class_new class_new_minivan,class | class thing | class course,"[class, new class, new, minivan, mercedes, ass...","[class, class thing, class course, class level...",[Mercedes Luxury Class Vehicles],"[class, new class, minivan, mercedes, driving ...","[class, new, minivan, assistance, driving, sys...","[The C-Class., In its class., The S-Class.]"
25,24,208,24_nsx_nx_crossover_supercar,nsx | nx | rx,"[nsx, nx, crossover, supercar, new, cx, cx 30,...","[nsx, nx, rx, cx, new generation, cx 30, ux, g...",[Next-Gen NSX Supercar Evolution],"[nsx, nx, supercar, cx, cx 30, engine, electri...","[crossover, supercar, new, performance, genera...","[It's a new generation of the NSX., To me the ..."
26,25,208,25_auto_la_los_los angeles,los angeles | angeles | la auto,"[auto, la, los, los angeles, angeles, detroit,...","[los angeles, angeles, la auto, la, right la, ...",[2015 Los Angeles Auto Show],"[los angeles, detroit, toronto, la auto, inter...","[auto, beach, international, season, city, wel...","[We started with you in Los Angeles, went to D..."
27,26,195,26_color_colors_blue_tone,different colors | colour | colors,"[color, colors, blue, tone, red, black, exteri...","[different colors, colour, colors, blue, color...",[Protonic Blue Color Options],"[color, colors, exterior colors, new color, co...","[color, colors, blue, tone, red, black, exteri...","[And this color?, And the color?, Our color co..."
28,27,189,27_elantra_elr_new elantra_elantra hybrid,elantra | new elantra | 2017 elantra,"[elantra, elr, new elantra, elantra hybrid, ne...","[elantra, new elantra, 2017 elantra, elantra l...",[Elantra Safety and Features Overview],"[elantra, elr, new elantra, elantra hybrid, 20...","[elantra, new, safety, generation, features, h...","[And I'm going to be back with Elantra., Well,..."
29,28,189,28_rav4_rav4 prime_prime_hybrid,rav4 prime | new rav4 | rav4,"[rav4, rav4 prime, prime, hybrid, road, trd, a...","[rav4 prime, new rav4, rav4, rav4 hybrid, 2023...",[RAV4 Prime Features and Performance],"[rav4 prime, trd road, plug hybrid, rav4 hybri...","[hybrid, road, available, plug, grades, grade,...","[On top of all that, RAV4 Prime is also highly..."
30,29,186,29_technology_technologies_tech_innovation,technology | new technology | technology new,"[technology, technologies, tech, innovation, a...","[technology, new technology, technology new, t...",[Innovations in Advanced Technology],"[technologies, tech, innovation, lot technolog...","[technology, technologies, tech, innovation, a...","[I've always been into technology., Technology..."
31,30,175,30_camry_toyota_toyota com_com,camry camry | camry | new camry,"[camry, toyota, toyota com, com, trd, new camr...","[camry camry, camry, new camry, camry features...",[Toyota Camry Features and Offerings],"[toyota, toyota com, trd, new camry, slash, ca...","[camry, visit, grades, drive, available, new, ...","[Well, that's more than the Camry., I own a Ca..."
32,31,174,31_wheels_inch_alloy_alloy wheels,alloy wheels | inch wheels | alloy wheel,"[wheels, inch, alloy, alloy wheels, 20 inch, i...","[alloy wheels, inch wheels, alloy wheel, wheel...",[Alloy Wheel Sizes and Designs],"[wheels, alloy wheels, 20 inch, inch alloy, in...","[wheels, inch, alloy, black, tires, wheel, inc...","[Or 19 inch alloy wheels on the rear., 20-inch..."
33,32,173,32_corolla_corolla hybrid_new corolla_hybrid,corolla hybrid | new corolla | corolla,"[corolla, corolla hybrid, new corolla, hybrid,...","[corolla hybrid, new corolla, corolla, corolla...",[Corolla Hybrid and Features],"[corolla, corolla hybrid, new corolla, corolla...","[hybrid, safety, new, grades, modern, lineup, ...",[It's a unique choice for both the Corolla and...
34,33,169,33_sonata_2018 sonata_new sonata_2018,2018 sonata | new sonata | sonata,"[sonata, 2018 sonata, new sonata, 2018, sonata...","[2018 sonata, new sonata, sonata, sonata comes...",[2018 Sonata Features and Technology],"[sonata, 2018 sonata, new sonata, sonata hybri...","[liter, turbo, safety, engine, hybrid, new, fe...","[The 2018 Sonata, our best Sonata ever., So th..."
35,34,168,34_oh_oh oh_uh_huh,oh | oh oh | oh yeah,"[oh, oh oh, uh, huh, hmm, mm, oh yeah, kidding...","[oh, oh oh, oh yeah, ah, um, yeah oh, uh, oh m...",[Expressions of Surprise and Reaction],"[whoa, yaw, boom, yeah oh, ooh ooh, excuse, li...","[hmm, , , , , , , , , ]","[Oh., Oh., Oh.]"
36,35,160,35_eqs_eqe_eq_mercedes,new eqs | eqs comes | new eqe,"[eqs, eqe, eq, mercedes, mercedes eq, new eqs,...","[new eqs, eqs comes, new eqe, eqs, eqe comes, ...",[Mercedes EQS Electric Vehicles],"[eqs, mercedes eq, new eqs, new eqe, eq boost,...","[new, electric, boost, driving, family, design...","[And the new EQS is no different., I'm about t..."
37,36,157,36_mustang_mach_mustang mach_really,mustang | know mustang | electric mustang,"[mustang, mach, mustang mach, really, know, id...","[mustang, know mustang, electric mustang, must...",[Mustang Electric Vehicle Excitement],"[mustang, mach, mustang mach, iconic, look lik...","[iconic, team, vehicle, customers, excited, lo...","[Do we call it a Mustang?, My Mustang is every..."
38,37,153,37_bye_bye bye_goodbye_say goodbye,bye bye | bye | goodbye,"[bye, bye bye, goodbye, say goodbye, say, time...","[bye bye, bye, goodbye, say goodbye, leave, sa...",[Farewells and Goodbyes],"[bye, bye bye, goodbye, say goodbye, time say,...","[bye, goodbye, mate, note, work, today, time, ...","[Bye-bye., Bye-bye for now., Bye-bye.]"
39,38,152,38_highlander_grand highlander_grand_suv,grand highlander | highlander exterior | highl...,"[highlander, grand highlander, grand, suv, hig...","[grand highlander, highlander exterior, highla...",[Grand Highlander Interior and Exterior],"[highlander, grand highlander, suv, highlander...","[standard, exterior, available, grades, end, w...",[That's what makes Grand Highlander's exterior...

### 輸出存檔

In [68]:
topic_info = topic_model.get_topic_info()
topic_info.to_csv("topic_info.csv", index=False, encoding="utf-8-sig")

## 5.3 OpenAI設定標籤

In [69]:
# or ChatGPT's labels
chatgpt_topic_labels = {topic: " | ".join(list(zip(*values))[0]) for topic, values in topic_model.topic_aspects_["OpenAI"].items()}
chatgpt_topic_labels[-1] = "Outlier Topic"
topic_model.set_topic_labels(chatgpt_topic_labels)

### 檢視

In [70]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,KeyBERT,OpenAI,MMR,POS,Representative_Docs
0,-1,19034,-1_new_like_car_នប,Outlier Topic,"[new, like, car, នប, just, នប នប, let, right, ...","[let, course, going, yeah, great, just, ll, do...",[Car Subscription and Entertainment Options],"[new, like, car, នប នប, look, great, performan...","[new, car, right, driving, look, time, great, ...","[Let's do it., The app is a Platinum Plan tria..."
1,0,4026,0_electric_charging_battery_engine,Electric Vehicle Power Systems,"[electric, charging, battery, engine, charge, ...","[electric car, electric vehicle, electric moto...",[Electric Vehicle Power Systems],"[electric, charging, hybrid, horsepower, ev, w...","[electric, battery, engine, charge, hybrid, po...","[The electric motor., By the way, fast chargin..."
2,1,2677,1_car_cars_vehicle_driving,Car Design and Experience,"[car, cars, vehicle, driving, drive, vehicles,...","[car car, car like, automobile, drive car, car...",[Car Design and Experience],"[cars, driving, vehicles, sedan, new, car car,...","[car, cars, vehicle, driving, vehicles, sedan,...","[That car is nothing else than ., It's about t..."
3,2,1474,2_display_screen_navigation_phone,Advanced Vehicle Display Systems,"[display, screen, navigation, phone, inch, sma...","[navigation, screen, screens, displays, displa...",[Advanced Vehicle Display Systems],"[screen, navigation, smartphone, button, andro...","[display, screen, navigation, phone, inch, sma...","[Through the multi-information display, the av..."
4,3,920,3_seats_seat_cargo_space,Seating and Cargo Space Features,"[seats, seat, cargo, space, rear, rear seats, ...","[seats, rear seats, passenger seat, seats avai...",[Seating and Cargo Space Features],"[seats, cargo, rear seats, trunk, seating, pas...","[seats, seat, cargo, space, rear, rear seats, ...","[The rear seats are all of the same., Well, wh..."
5,4,751,4_das_die_en_wir,Innovations in Automotive Development,"[das, die, en, wir, der, la, dan, een, yang, det]","[einen, das, einem, auf, der, zuffenhausen, ko...",[Innovations in Automotive Development],"[das, der, det, auto, als, van, vi, auf, il, e...","[die, der, een, auto, du, als, man, einen, op,...","[Die Entwicklung hat sich insofern verändert, ..."
6,5,684,5_brand_customers_products_market,Sustainable Brand Growth Strategy,"[brand, customers, products, market, product, ...","[customers want, customers, consumers, custome...",[Sustainable Brand Growth Strategy],"[brand, customers, market, sales, new products...","[brand, customers, products, market, product, ...",[While protecting the value of our brand and o...
7,6,679,6_led_light_grille_lights,Adaptive LED Headlight Design,"[led, light, grille, lights, headlights, light...","[led headlights, headlights, led headlamps, le...",[Adaptive LED Headlight Design],"[headlights, lighting, led headlights, headlam...","[light, grille, lights, headlights, lighting, ...",[Pixel-inspired lighting signature with LED he...
8,7,631,7_thank thank_thank_thank guys_guys thank,Expressions of Gratitude,"[thank thank, thank, thank guys, guys thank, g...","[thank, thank thank, thank guys, guys thank, ,...",[Expressions of Gratitude],"[thank thank, thank, thank guys, guys thank, g...","[guys, , , , , , , , , ]","[Thank you., Thank you., Thank you.]"
9,8,599,8_different_did_doing_lot,Embracing Change and Progress,"[different, did, doing, lot, ve, new, change, ...","[things going, going doing, doing, approach, w...",[Embracing Change and Progress],"[different, did, change, challenge, things, fo...","[different, lot, new, challenge, things, peopl...","[And we're doing it the way., We're going to b..."
10,9,547,9_president_vice_welcome_vice president,Executive Leadership Introductions,"[president, vice, welcome, vice president, hi,...","[vice chairman, executive vice, vice president...",[Executive Leadership Introductions],"[president, vice, vice president, hi, ceo, gen...","[president, vice, gentlemen, ladies, manager, ...",[Please welcome Group Vice President and Gener...
11,10,490,10_design_designers_modern_beautiful,Innovative Design Concepts and Excellence,"[design, designers, modern, beautiful, know, s...","[design great, good design, new design, import...",[Innovative Design Concepts and Excellence],"[designers, sculpture, design team, expressive...","[design, designers, modern, beautiful, sculptu...","[It's a great design., It is a great design, a..."
12,11,436,11_air_climate_temperature_rear,Advanced Climate Control Systems,"[air, climate, temperature, rear, cold, climat...","[airflow, air flow, air, air conditioning, ven...",[Advanced Climate Control Systems],"[temperature, climate control, cooling, dramat...","[air, climate, temperature, rear, cold, hot, c...",[It will circulate through the outside air in....
13,12,417,12_assist_lane_collision_braking,Advanced Driver Assistance Systems,"[assist, lane, collision, braking, cruise, eme...","[driving assist, lane assist, safety features,...",[Advanced Driver Assistance Systems],"[assist, lane, cruise control, emergency braki...","[assist, lane, collision, braking, cruise, eme...",[These include forward collision avoidance ass...
14,13,326,13_interior_exterior_interior interior_interio...,Interior Design and Space Experience,"[interior, exterior, interior interior, interi...","[interior interior, look interior, interior, i...",[Interior Design and Space Experience],"[interior interior, interior design, look inte...","[interior, exterior, interior design, inside, ...","[And the interior as well., And, you can also ..."
15,14,315,14_steering_steering wheel_wheel_braking,Steering and Driving Dynamics,"[steering, steering wheel, wheel, braking, bra...","[steering, steering wheel, steering feel, wrap...",[Steering and Driving Dynamics],"[steering, steering wheel, steering feel, rege...","[steering, wheel, braking, brake, pedal, rear,...","[The steering., They do move with the steering..."
16,15,305,15_yeah yeah_yeah_yep_sorry yeah,Casual Affirmations and Apologies,"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[yeah, yeah yeah, yep, , , , , , , ]",[Casual Affirmations and Apologies],"[yeah yeah, yeah, yep, sorry yeah, heck, dude,...","[sorry, , , , , , , , , ]","[Yeah., Yeah., Yeah.]"
17,16,298,16_son___,Relationship with Son,"[son, , , , , , , , , ]","[, , , , , , , , , ]",[Relationship with Son],"[son, , , , , , , , , , , , , , , , , , , , , ...","[, , , , , , , , , ]","[., ., Son.]"
18,17,279,17_okay_okay okay_absolutely_sure,Affirmative Responses and Agreement,"[okay, okay okay, absolutely, sure, alright, s...","[okay, ok, okay okay, alright, okay yeah, yeah...",[Affirmative Responses and Agreement],"[alright alright, absolutely yeah, fine fine, ...","[sure, unreal, cool, folks, stuff, great, , , , ]","[Okay., Okay., Okay.]"
19,18,272,18_ioniq_life important_smartsense_charging,IONIQ Electric Vehicle Features,"[ioniq, life important, smartsense, charging, ...","[ioniq, ioniq limited, ioniq hybrid, vehicle i...",[IONIQ Electric Vehicle Features],"[ioniq, life important, smartsense, charging, ...","[charging, platform, life, electric, important...","[is a very important part of the IONIQ life., ..."
20,19,257,19_s60_xc40_xc90_xc40 recharge,XC40 Recharge Electric Support Technology,"[s60, xc40, xc90, xc40 recharge, recharge, new...","[xc40 recharge, xc40, recharge, xc60, xc90, el...",[XC40 Recharge Electric Support Technology],"[s60, xc40, xc90, xc40 recharge, new s60, s90,...","[recharge, new, safety, cars, experience, car,...",[We're not going to connect with the XC40 Rech...
21,20,256,20_cool_nice_amazing_pretty,Expressions of Enthusiastic Approval,"[cool, nice, amazing, pretty, really, awesome,...","[really cool, looks cool, great cool, pretty c...",[Expressions of Enthusiastic Approval],"[pretty, really cool, pretty cool, just incred...","[cool, nice, amazing, awesome, incredible, gre...","[It's that cool., So it looks really cool., It..."
22,21,254,21_prius_prius prime_prime_hybrid,Prius Hybrid Vehicle Overview,"[prius, prius prime, prime, hybrid, efficiency...","[prius, new prius, prius prime, hybrid prius, ...",[Prius Hybrid Vehicle Overview],"[prius, prius prime, hybrid, new prius, safety...","[hybrid, efficiency, family, safety, drive, pl...","[Prius., Prius., Prius.]"
23,22,239,22_thank_joining_today_thank joining,Gratitude for Joining Event,"[thank, joining, today, thank joining, thanks,...","[thank joining, thanks joining, joining today,...",[Gratitude for Joining Event],"[thank joining, thank time, today thank, joini...","[today, thanks, welcome, attention, day, gentl...","[Thank you for joining us., Thank you for join..."
24,23,211,23_class_new class_new_minivan,Mercedes Luxury Class Vehicles,"[class, new class, new, minivan, mercedes, ass...","[class, class thing, class course, class level...",[Mercedes Luxury Class Vehicles],"[class, new class, minivan, mercedes, driving ...","[class, new, minivan, assistance, driving, sys...","[The C-Class., In its class., The S-Class.]"
25,24,208,24_nsx_nx_crossover_supercar,Next-Gen NSX Supercar Evolution,"[nsx, nx, crossover, supercar, new, cx, cx 30,...","[nsx, nx, rx, cx, new generation, cx 30, ux, g...",[Next-Gen NSX Supercar Evolution],"[nsx, nx, supercar, cx, cx 30, engine, electri...","[crossover, supercar, new, performance, genera...","[It's a new generation of the NSX., To me the ..."
26,25,208,25_auto_la_los_los angeles,2015 Los Angeles Auto Show,"[auto, la, los, los angeles, angeles, detroit,...","[los angeles, angeles, la auto, la, right la, ...",[2015 Los Angeles Auto Show],"[los angeles, detroit, toronto, la auto, inter...","[auto, beach, international, season, city, wel...","[We started with you in Los Angeles, went to D..."
27,26,195,26_color_colors_blue_tone,Protonic Blue Color Options,"[color, colors, blue, tone, red, black, exteri...","[different colors, colour, colors, blue, color...",[Protonic Blue Color Options],"[color, colors, exterior colors, new color, co...","[color, colors, blue, tone, red, black, exteri...","[And this color?, And the color?, Our color co..."
28,27,189,27_elantra_elr_new elantra_elantra hybrid,Elantra Safety and Features Overview,"[elantra, elr, new elantra, elantra hybrid, ne...","[elantra, new elantra, 2017 elantra, elantra l...",[Elantra Safety and Features Overview],"[elantra, elr, new elantra, elantra hybrid, 20...","[elantra, new, safety, generation, features, h...","[And I'm going to be back with Elantra., Well,..."
29,28,189,28_rav4_rav4 prime_prime_hybrid,RAV4 Prime Features and Performance,"[rav4, rav4 prime, prime, hybrid, road, trd, a...","[rav4 prime, new rav4, rav4, rav4 hybrid, 2023...",[RAV4 Prime Features and Performance],"[rav4 prime, trd road, plug hybrid, rav4 hybri...","[hybrid, road, available, plug, grades, grade,...","[On top of all that, RAV4 Prime is also highly..."
30,29,186,29_technology_technologies_tech_innovation,Innovations in Advanced Technology,"[technology, technologies, tech, innovation, a...","[technology, new technology, technology new, t...",[Innovations in Advanced Technology],"[technologies, tech, innovation, lot technolog...","[technology, technologies, tech, innovation, a...","[I've always been into technology., Technology..."
31,30,175,30_camry_toyota_toyota com_com,Toyota Camry Features and Offerings,"[camry, toyota, toyota com, com, trd, new camr...","[camry camry, camry, new camry, camry features...",[Toyota Camry Features and Offerings],"[toyota, toyota com, trd, new camry, slash, ca...","[camry, visit, grades, drive, available, new, ...","[Well, that's more than the Camry., I own a Ca..."
32,31,174,31_wheels_inch_alloy_alloy wheels,Alloy Wheel Sizes and Designs,"[wheels, inch, alloy, alloy wheels, 20 inch, i...","[alloy wheels, inch wheels, alloy wheel, wheel...",[Alloy Wheel Sizes and Designs],"[wheels, alloy wheels, 20 inch, inch alloy, in...","[wheels, inch, alloy, black, tires, wheel, inc...","[Or 19 inch alloy wheels on the rear., 20-inch..."
33,32,173,32_corolla_corolla hybrid_new corolla_hybrid,Corolla Hybrid and Features,"[corolla, corolla hybrid, new corolla, hybrid,...","[corolla hybrid, new corolla, corolla, corolla...",[Corolla Hybrid and Features],"[corolla, corolla hybrid, new corolla, corolla...","[hybrid, safety, new, grades, modern, lineup, ...",[It's a unique choice for both the Corolla and...
34,33,169,33_sonata_2018 sonata_new sonata_2018,2018 Sonata Features and Technology,"[sonata, 2018 sonata, new sonata, 2018, sonata...","[2018 sonata, new sonata, sonata, sonata comes...",[2018 Sonata Features and Technology],"[sonata, 2018 sonata, new sonata, sonata hybri...","[liter, turbo, safety, engine, hybrid, new, fe...","[The 2018 Sonata, our best Sonata ever., So th..."
35,34,168,34_oh_oh oh_uh_huh,Expressions of Surprise and Reaction,"[oh, oh oh, uh, huh, hmm, mm, oh yeah, kidding...","[oh, oh oh, oh yeah, ah, um, yeah oh, uh, oh m...",[Expressions of Surprise and Reaction],"[whoa, yaw, boom, yeah oh, ooh ooh, excuse, li...","[hmm, , , , , , , , , ]","[Oh., Oh., Oh.]"
36,35,160,35_eqs_eqe_eq_mercedes,Mercedes EQS Electric Vehicles,"[eqs, eqe, eq, mercedes, mercedes eq, new eqs,...","[new eqs, eqs comes, new eqe, eqs, eqe comes, ...",[Mercedes EQS Electric Vehicles],"[eqs, mercedes eq, new eqs, new eqe, eq boost,...","[new, electric, boost, driving, family, design...","[And the new EQS is no different., I'm about t..."
37,36,157,36_mustang_mach_mustang mach_really,Mustang Electric Vehicle Excitement,"[mustang, mach, mustang mach, really, know, id...","[mustang, know mustang, electric mustang, must...",[Mustang Electric Vehicle Excitement],"[mustang, mach, mustang mach, iconic, look lik...","[iconic, team, vehicle, customers, excited, lo...","[Do we call it a Mustang?, My Mustang is every..."
38,37,153,37_bye_bye bye_goodbye_say goodbye,Farewells and Goodbyes,"[bye, bye bye, goodbye, say goodbye, say, time...","[bye bye, bye, goodbye, say goodbye, leave, sa...",[Farewells and Goodbyes],"[bye, bye bye, goodbye, say goodbye, time say,...","[bye, goodbye, mate, note, work, today, time, ...","[Bye-bye., Bye-bye for now., Bye-bye.]"
39,38,152,38_highlander_grand highlander_grand_suv,Grand Highlander Interior and Exterior,"[highlander, grand highlander, grand, suv, hig...","[grand highlander, highlander exterior, highla...",[Grand Highlander Interior and Exterior],"[highlander, grand highlander, suv, highlander...","[standard, exterior, available, grades, end, w...",[That's what makes Grand Highlander's exterior...

### 輸出存檔

In [71]:
topic_info = topic_model.get_topic_info()
topic_info.to_csv("topic_info.csv", index=False, encoding="utf-8-sig")

# 6️⃣ 可視化主題

## 6.1 topic_model.visualize_topics()

In [72]:
topic_model.visualize_topics(custom_labels=True)
fig = topic_model.visualize_topics(custom_labels=True)
fig.write_html("visualize_topics.html")

## 6.2 topic_model.visualize_hierarchy()

In [73]:
topic_model.visualize_hierarchy(custom_labels=True)
fig = topic_model.visualize_hierarchy(custom_labels=True)
fig.write_html("visualize_hierarchy.html")

# 7️⃣ 儲存模型

In [75]:
embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
topic_model.save("BERTopic_ver.2.1_Clean", serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model)